#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export PHPENV_DEBUG=1
  shift
fi

if [ -n "$PHPENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

if enable -f "${0%/*}"/../libexec/phpenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  if [ -n "$PHPENV_NATIVE_EXT" ]; then
    echo "phpenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "phpenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}
fi

if [ -z "${PHPENV_ROOT}" ]; then
  PHPENV_ROOT="${HOME}/.phpenv"
else
  PHPENV_ROOT="${PHPENV_ROOT%/}"
fi
export PHPENV_ROOT

if [ -z "${PHPENV_DIR}" ]; then
  PHPENV_DIR="$(pwd)"
else
  cd "$PHPENV_DIR" 2>/dev/null || {
    echo "phpenv: cannot change working directory to \`$PHPENV_DIR'"
    exit 1
  } >&2
  PHPENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export PHPENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${PHPENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${PHPENV_ROOT}/phpenv.d"
if [ "${bin_path%/*}" != "$PHPENV_ROOT" ]; then
  # Add phpenv's own `phpenv.d` unless phpenv was cloned to PHPENV_ROOT
  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${bin_path%/*}/phpenv.d"
fi
PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:/usr/local/etc/phpenv.d:/etc/phpenv.d:/usr/lib/phpenv/hooks"
for plugin_hook in "${PHPENV_ROOT}/plugins/"*/etc/phpenv.d; do
  PHPENV_HOOK_PATH="${PHPENV_HOOK_PATH}:${plugin_hook}"
done
export PHPENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(phpenv---version)\n$(phpenv-help)" >&2
  ;;
"-v" )
  exec phpenv---version
  ;;
* )
  command_path="$(command -v "phpenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "phpenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac